{{- if .Values.messageTemplate -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keybase-alertmanager.fullname" . }}
  labels:
{{ include "keybase-alertmanager.labels" . | indent 4 }}
data:
  message.tmpl: |
{{ .Values.messageTemplate | indent 4 }}
{{end}}
